# Notes for YouTube Python Tutorials
## Complete Python NumPy Tutorial (Creating Arrays, Indexing, Math, Statistics, Reshaping)
https://www.youtube.com/watch?v=GB9ByFAIAH4

In [1]:
import numpy as np

## The Basics

In [2]:
a = np.array([1, 2, 3]) # by default, dtype is 'int32'
print(a)
print(a.dtype)

[1 2 3]
int32


In [3]:
a = np.array([1, 2, 3], dtype='int16')
print(a)
print(a.dtype)

[1 2 3]
int16


In [4]:
# Change back to default
a = np.array([1, 2, 3])

In [5]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]]) # don't miss comma
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [7]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


## Accessing/Changing specific elements, rows, columns, etc

In [8]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],
              [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
# Get a specific element [r, c]
a[1, 5]

13

In [10]:
# Get a specific row or column
print(a[0, :])
print(a[:, 2])

[1 2 3 4 5 6 7]
[ 3 10]


In [11]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [12]:
# Change a value
a[1, 5] = 20 # change a value
print(a)

a[:, 2] = 5 # change all values to a single number
print(a)

a[:, 2] = [1, 2] # change a vector
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [13]:
# 3-D example
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
# Get specific element (work outside in)
b[0, 1, 1]
# 0 -> [[1, 2],[3, 4]]
# 1 -> [3, 4]
# 1 -> 4

4

# Initializing Different Types of Arrays

In [15]:
# All 0s matrix
print(np.zeros(5))
print()
print(np.zeros((2, 3))) # It should be a tuple (2, 3).
print()
print(np.zeros((2, 3, 3)))

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [16]:
# All 1s matrix
print(np.ones((4, 2, 2)))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [17]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [18]:
# Any other number (full_like)
np.full_like(a, 4) # The same size as a

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [19]:
# Random decimal numbers
np.random.rand(4, 2) # Don't pass a tuple

array([[0.93877067, 0.6938183 ],
       [0.20499744, 0.05043294],
       [0.01331303, 0.90828714],
       [0.11723022, 0.28620952]])

In [20]:
# Random integer values
np.random.randint(7, size=(3, 3)) # from 0 to 7 (exclude)

array([[1, 3, 4],
       [0, 6, 4],
       [4, 4, 5]])

In [21]:
# Random integer values
np.random.randint(4, 7, size=(3, 3)) # from 4 to 7 (exclude)

array([[6, 6, 6],
       [4, 5, 5],
       [5, 4, 6]])

In [22]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [24]:
# Repeat an array
arr = np.array([[1, 2, 3]]) # There are two pairs of []
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [25]:
# Quiz
output = np.ones((5, 5))
z = np.zeros((3, 3))
output[1:4, 1:4] = z # output[1:-1, 1:-1] = z
output[2, 2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!!

In [26]:
# Both a and b were modified.
a = np.array([1, 2, 3])
b = a
b[0] = 100

print(a)
print(b)

[100   2   3]
[100   2   3]


In [27]:
# Fix the previous issue.
a = np.array([1, 2, 3])
b = a.copy() # use copy function
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [28]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [29]:
a + 2 # OR a += 2

array([3, 4, 5, 6])

In [30]:
a - 2

array([-1,  0,  1,  2])

In [31]:
a * 2

array([2, 4, 6, 8])

In [32]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [33]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [34]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [35]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [36]:
# Matrix multiplication
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [37]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

Determinant<br>
Trace<br>
Singular Vector Decomposition<br>
Eigenvalues<br>
Matrix Norm<br>
Inverse<br>
Etc...<br>

## Statistics

In [38]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
# Overall min
np.min(stats)

1

In [40]:
# min based on columns
np.min(stats, axis=0)

array([1, 2, 3])

In [41]:
# min based on rows
np.min(stats, axis=1)

array([1, 4])

In [42]:
# Overall max
np.max(stats)

6

In [43]:
# Overall sum
np.sum(stats)

21

## Reorganizing Arrays

In [44]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous
### Load Data from File

In [48]:
filedata = np.genfromtxt('Python Data/numpy_sample_data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [49]:
# Change data from float to int
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [50]:
### Boolean Masking and Advanced Indexing
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [51]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [52]:
# You can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [53]:
np.any(filedata > 50, axis=0) # by columns

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [54]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [55]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [56]:
# Quiz
matrix = np.array([x for x in range(1, 31)])
matrix = matrix.reshape(6, 5)

In [57]:
output = matrix[2:4, 0:2]
print(output)

[[11 12]
 [16 17]]


In [58]:
output = matrix[[0, 1, 2, 3], [1, 2, 3, 4]]
print(output)

[ 2  8 14 20]


In [59]:
output = matrix[[0, 4, 5], 3:]
print(output)

[[ 4  5]
 [24 25]
 [29 30]]
